### ISSUE TITLE
Error getting devices: Error: UserOpenTwoFactorAuth

### ISSUE THREAD

**Issue by pjotal** [misenhower/homebridge-wyze-connected-home#1]
Provided all necessary information in config.json but it's not working due to failing on two factor authentication.

here is the error message captured from the logs:
```
5/14/2020, 9:38:59 AM > [5/14/2020, 9:38:59 AM] [Wyze] Refreshing devices...
5/14/2020, 9:38:59 AM > [5/14/2020, 9:38:59 AM] [Wyze] Performing request: app/user/login
5/14/2020, 9:38:59 AM > [5/14/2020, 9:38:59 AM] [Wyze] API response: {"ts":<long-number-here>,"code":"<4-digits-here>","msg":"UserOpenTwoFactorAuth","data":{}}
5/14/2020, 9:38:59 AM > [5/14/2020, 9:38:59 AM] [Wyze] Error getting devices: Error: UserOpenTwoFactorAuth
```

**Comment by misenhower** [comment]
2FA isn't currently supported, but I'll look into this in the future to see if I can implement it via refresh tokens. I'd suggest disabling 2FA for now if you want to use this plugin. Thanks!

**Comment by pjotal** [comment]
i noticed that if the user provides all info you request in your constructor (except refreshToken which is not necessary) in the `config.json` he won't need to perform the login method. therefore, you can bypass it as an alternative. from what i saw in your code this is already the case.

i guess you just need to collect those in your `getClient()`

**Comment by pjotal** [comment]
well.. good news for you.
in the PR i just submitted i added support for 2FA as well :)
took the chance to enhance a bit the error handling and logging here and there, nothing major.
